/*
 * InventoryControlFrameView.java
 */

package org.workplicity.inventorycontrol.desktop.inventorycontrolframe;

import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.workplicity.inventorycontrol.desktop.eventhandler.EventDialog;
import org.workplicity.inventorycontrol.desktop.eventhandler.EventEditor;
import org.workplicity.inventorycontrol.desktop.locationhandler.LocationDialog;
import org.workplicity.inventorycontrol.desktop.locationhandler.LocationEditor;
import org.workplicity.inventorycontrol.desktop.itemtypehandler.ItemTypeDialog;
import org.workplicity.inventorycontrol.desktop.itemtypehandler.ItemTypeEditor;
import org.workplicity.inventorycontrol.desktop.userhandler.UserDialog;
import org.workplicity.inventorycontrol.desktop.userhandler.UserEditor;
import org.workplicity.inventorycontrol.desktop.stockhandler.StockDialog;
import org.workplicity.inventorycontrol.desktop.stockhandler.StockEditor;
import org.workplicity.inventorycontrol.desktop.itemhandler.ItemDialog;
import org.workplicity.inventorycontrol.desktop.itemhandler.ItemEditor;

/**
 * The application's main frame.
 */
public class InventoryControlFrameView extends FrameView {

    public InventoryControlFrameView(SingleFrameApplication app) {
        super(app);

        initComponents();

        try
        {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex)
        {
            System.out.println("Sorry, Dave, I can't do that.");
        }
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = InventoryControlFrameApp.getApplication().getMainFrame();
            aboutBox = new InventoryControlFrameAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        InventoryControlFrameApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        inventoryMenu = new javax.swing.JMenu();
        showItemsMenuItem = new javax.swing.JMenuItem();
        showItemTypeMenuItem = new javax.swing.JMenuItem();
        showStockMenuItem = new javax.swing.JMenuItem();
        locationMenu = new javax.swing.JMenu();
        showLocationsMenuItem = new javax.swing.JMenuItem();
        eventMenu = new javax.swing.JMenu();
        showEventsMenuItem = new javax.swing.JMenuItem();
        userMenu = new javax.swing.JMenu();
        showUsersMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(InventoryControlFrameView.class);
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(InventoryControlFrameView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        inventoryMenu.setText(resourceMap.getString("inventoryMenu.text")); // NOI18N
        inventoryMenu.setName("inventoryMenu"); // NOI18N

        showItemsMenuItem.setText(resourceMap.getString("showItemsMenuItem.text")); // NOI18N
        showItemsMenuItem.setName("showItemsMenuItem"); // NOI18N
        showItemsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showItemsMenuItemActionPerformed(evt);
            }
        });
        inventoryMenu.add(showItemsMenuItem);

        showItemTypeMenuItem.setText(resourceMap.getString("showItemTypeMenuItem.text")); // NOI18N
        showItemTypeMenuItem.setName("showItemTypeMenuItem"); // NOI18N
        showItemTypeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showItemTypeMenuItemActionPerformed(evt);
            }
        });
        inventoryMenu.add(showItemTypeMenuItem);

        showStockMenuItem.setText(resourceMap.getString("showStockMenuItem.text")); // NOI18N
        showStockMenuItem.setName("showStockMenuItem"); // NOI18N
        showStockMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStockMenuItemActionPerformed(evt);
            }
        });
        inventoryMenu.add(showStockMenuItem);

        menuBar.add(inventoryMenu);

        locationMenu.setText(resourceMap.getString("locationMenu.text")); // NOI18N
        locationMenu.setName("locationMenu"); // NOI18N

        showLocationsMenuItem.setText(resourceMap.getString("showLocationsMenuItem.text")); // NOI18N
        showLocationsMenuItem.setName("showLocationsMenuItem"); // NOI18N
        showLocationsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLocationsMenuItemActionPerformed(evt);
            }
        });
        locationMenu.add(showLocationsMenuItem);

        menuBar.add(locationMenu);

        eventMenu.setText(resourceMap.getString("eventMenu.text")); // NOI18N
        eventMenu.setName("eventMenu"); // NOI18N
        eventMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventMenuActionPerformed(evt);
            }
        });

        showEventsMenuItem.setText(resourceMap.getString("showEventsMenuItem.text")); // NOI18N
        showEventsMenuItem.setName("showEventsMenuItem"); // NOI18N
        showEventsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEventsMenuItemActionPerformed(evt);
            }
        });
        eventMenu.add(showEventsMenuItem);

        menuBar.add(eventMenu);

        userMenu.setText(resourceMap.getString("userMenu.text")); // NOI18N
        userMenu.setName("userMenu"); // NOI18N

        showUsersMenuItem.setText(resourceMap.getString("showUsersMenuItem.text")); // NOI18N
        showUsersMenuItem.setName("showUsersMenuItem"); // NOI18N
        showUsersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUsersMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(showUsersMenuItem);

        menuBar.add(userMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void eventMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventMenuActionPerformed

    }//GEN-LAST:event_eventMenuActionPerformed

    private void showItemsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showItemsMenuItemActionPerformed
        ItemDialog handler = new ItemDialog(this.getFrame(), true);
        handler.setVisible(true);
        handler.dispose();
    }//GEN-LAST:event_showItemsMenuItemActionPerformed

    private void showItemTypeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showItemTypeMenuItemActionPerformed
        ItemTypeDialog handler = new ItemTypeDialog(this.getFrame(), true);
        handler.setVisible(true);
        handler.dispose();
    }//GEN-LAST:event_showItemTypeMenuItemActionPerformed

    private void showUsersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUsersMenuItemActionPerformed
        UserDialog handler = new UserDialog(this.getFrame(), true);
        handler.setVisible(true);
        handler.dispose();
    }//GEN-LAST:event_showUsersMenuItemActionPerformed

    private void showLocationsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLocationsMenuItemActionPerformed
        LocationDialog handler = new LocationDialog(this.getFrame(), true);
        handler.setVisible(true);
        handler.dispose();
    }//GEN-LAST:event_showLocationsMenuItemActionPerformed

    private void showStockMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStockMenuItemActionPerformed
        StockDialog handler = new StockDialog(this.getFrame(), true);
        handler.setVisible(true);
        handler.dispose();
    }//GEN-LAST:event_showStockMenuItemActionPerformed

    private void showEventsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEventsMenuItemActionPerformed
        EventDialog handler = new EventDialog(this.getFrame(), true);
        handler.setVisible(true);
        handler.dispose();
    }//GEN-LAST:event_showEventsMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu eventMenu;
    private javax.swing.JMenu inventoryMenu;
    private javax.swing.JMenu locationMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem showEventsMenuItem;
    private javax.swing.JMenuItem showItemTypeMenuItem;
    private javax.swing.JMenuItem showItemsMenuItem;
    private javax.swing.JMenuItem showLocationsMenuItem;
    private javax.swing.JMenuItem showStockMenuItem;
    private javax.swing.JMenuItem showUsersMenuItem;
    private javax.swing.JMenu userMenu;
    // End of variables declaration//GEN-END:variables

    private JDialog aboutBox;
}
