/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItemTypeDialog.java
 *
 * Created on Feb 27, 2011, 11:13:45 PM
 */

package org.workplicity.inventorycontrol.desktop.itemtypehandler;

/**
 *
 * @author Neal
 */
public class ItemTypeDialog extends javax.swing.JDialog {

    /** Creates new form ItemTypeDialog */
    public ItemTypeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try
        {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex)
        {
            System.out.println("Sorry, Dave, I can't do that.");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemTypes = new javax.swing.JTable();
        btnCreateItemType = new javax.swing.JButton();
        btnDeleteItemType = new javax.swing.JButton();
        btnUpdateItemType = new javax.swing.JButton();
        btnDisplayItemType = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblItemTypes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item Type ID", "Item Type Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItemTypes);

        btnCreateItemType.setText("Create Item Type");
        btnCreateItemType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateItemTypeActionPerformed(evt);
            }
        });

        btnDeleteItemType.setText("Delete Selected Item Type");
        btnDeleteItemType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemTypeActionPerformed(evt);
            }
        });

        btnUpdateItemType.setText("Update Selected Item Type");
        btnUpdateItemType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemTypeActionPerformed(evt);
            }
        });

        btnDisplayItemType.setText("Display Selected Item Type");
        btnDisplayItemType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayItemTypeActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClose)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnDisplayItemType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCreateItemType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnDeleteItemType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateItemType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateItemType)
                    .addComponent(btnDisplayItemType, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateItemType)
                    .addComponent(btnDeleteItemType))
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateItemTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateItemTypeActionPerformed
        ItemTypeEditor editor = new ItemTypeEditor(new Object(), true);
        editor.setVisible(true);
        editor.dispose();
    }//GEN-LAST:event_btnCreateItemTypeActionPerformed

    private void btnDisplayItemTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayItemTypeActionPerformed
        ItemTypeEditor editor = new ItemTypeEditor(new Object(), false);
        editor.setVisible(true);
        editor.dispose();
    }//GEN-LAST:event_btnDisplayItemTypeActionPerformed

    private void btnUpdateItemTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemTypeActionPerformed
        ItemTypeEditor editor = new ItemTypeEditor(new Object(), false);
        editor.setVisible(true);
        editor.dispose();
    }//GEN-LAST:event_btnUpdateItemTypeActionPerformed

    private void btnDeleteItemTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteItemTypeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ItemTypeDialog dialog = new ItemTypeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreateItemType;
    private javax.swing.JButton btnDeleteItemType;
    private javax.swing.JButton btnDisplayItemType;
    private javax.swing.JButton btnUpdateItemType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItemTypes;
    // End of variables declaration//GEN-END:variables

}
