/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LocationDialog.java
 *
 * Created on Mar 1, 2011, 10:51:50 PM
 */

package org.workplicity.inventorycontrol.desktop.locationhandler;

/**
 *
 * @author Neal
 */
public class LocationDialog extends javax.swing.JDialog {

    /** Creates new form LocationDialog */
    public LocationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try
        {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex)
        {
            System.out.println("Sorry, Dave, I can't do that.");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        locationsTable = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();
        createLocationButton = new javax.swing.JButton();
        displayLocationButton = new javax.swing.JButton();
        updateLocationButton = new javax.swing.JButton();
        deleteLocationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        locationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Location ID", "Building Name", "Room Number"
            }
        ));
        jScrollPane1.setViewportView(locationsTable);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        createLocationButton.setText("Create Location");
        createLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLocationButtonActionPerformed(evt);
            }
        });

        displayLocationButton.setText("Display Selected Location");
        displayLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayLocationButtonActionPerformed(evt);
            }
        });

        updateLocationButton.setText("Update Selected Location");
        updateLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLocationButtonActionPerformed(evt);
            }
        });

        deleteLocationButton.setText("Delete Selected Location");
        deleteLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLocationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(createLocationButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displayLocationButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateLocationButton)
                            .addComponent(deleteLocationButton)))
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayLocationButton)
                    .addComponent(updateLocationButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLocationButton)
                    .addComponent(deleteLocationButton))
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayLocationButtonActionPerformed
        LocationEditor editor = new LocationEditor(new Object(), false);
        editor.setVisible(true);
        editor.dispose();
    }//GEN-LAST:event_displayLocationButtonActionPerformed

    private void createLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLocationButtonActionPerformed
        LocationEditor editor = new LocationEditor(new Object(), true);
        editor.setVisible(true);
        editor.dispose();
    }//GEN-LAST:event_createLocationButtonActionPerformed

    private void updateLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLocationButtonActionPerformed
        LocationEditor editor = new LocationEditor(new Object(), true);
        editor.setVisible(true);
        editor.dispose();
    }//GEN-LAST:event_updateLocationButtonActionPerformed

    private void deleteLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLocationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteLocationButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LocationDialog dialog = new LocationDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton createLocationButton;
    private javax.swing.JButton deleteLocationButton;
    private javax.swing.JButton displayLocationButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable locationsTable;
    private javax.swing.JButton updateLocationButton;
    // End of variables declaration//GEN-END:variables

}
